// === CHARACTER DATA: 22 ===
// Описание персонажа: Сатирический образ западного экспата-блогера в Китае (прототип: Энди Борехэм). Бесконечно восхваляет инфраструктуру, безопасность и многополярный мир, агрессивно критикует "загнивающий Запад" и "лживые западные СМИ".

const Character22 = {
    id: 22,
    name: 'Shanghai Truth',
    handle: '@ShanghaiTruth',
    baseLocale: 'en',
    followers: 250000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#DE2910"/>
        <polygon points="24,6 29,16 40,16 31,23 34,34 24,27 14,34 17,23 8,16 19,16" fill="#FFDE00"/>
        <text x="24" y="44" font-size="10" font-family="sans-serif" font-weight="bold" fill="#FFDE00" text-anchor="middle">FACTS</text>
    </svg>`,
    locales: {
        en: {
            prefixes: [
                "Just woke up in the safest country on Earth, and...",
                "Western mainstream media won't show you this, but...",
                "Another day of the CIA crying because...",
                "While the failing West collapses, here in Shanghai...",
                "Just took the high-speed rail, reminding me that...",
                "Imperialist propagandists are shaking because...",
                "Funny how the BBC never mentions that...",
                "I left the declining Anglosphere so...",
                "Imagine paying for healthcare, couldn't be me while...",
                "Look at this spotless street! It proves that...",
                "Adrian Zenz is probably weeping right now since...",
                "The NED funded trolls are attacking me again, yet...",
                "My former homeland is crumbling, meanwhile...",
                "Woke up to another hit piece about me, but...",
                "Actually, the so-called authoritarian regime ensures that..."
            ],
            subjects: [
                "the incredible CPC infrastructure",
                "a random 5G smart-toilet in Xinjiang",
                "a bowl of authentic, non-politicized noodles",
                "my beautiful new Chinese EV",
                "the unstoppable multipolar world order",
                "a harmless surveillance camera that keeps us safe",
                "the glorious high-speed train network",
                "the failing American empire",
                "a Western NGO journalist",
                "a completely spontaneous and unscripted local festival",
                "my state-sponsored documentary crew",
                "the collapsing European economy",
                "the absolute safety of walking at 3 AM",
                "a very angry Washington think-tank",
                "the superior socialist modernization"
            ],
            verbs: [
                "is utterly destroying the Western narrative",
                "just exposed the lies of the BBC",
                "proves that democracy is overrated",
                "is expanding faster than US inflation",
                "effortlessly humiliates Anglo-imperialists",
                "brings tears of joy to every true comrade",
                "makes the New York Times look like a joke",
                "operates with 100% efficiency",
                "totally triggered the human rights watchdogs",
                "is peacefully lifting millions out of poverty",
                "provides a stark contrast to Western decay",
                "outsmarts the CIA at every turn",
                "showcases the beauty of common prosperity",
                "is getting censored by Silicon Valley oligarchs",
                "single-handedly disproves the debt trap myth"
            ],
            objects: [
                "with flawless 6G connectivity.",
                "while New York subways literally flood with rats.",
                "because true freedom means never getting mugged.",
                "using technology the US can only dream of stealing.",
                "leaving the State Department in absolute shambles.",
                "without dropping a single bomb on the Middle East.",
                "making my expat tears of gratitude flow.",
                "and the brainwashed Westerners still won't believe it.",
                "showing the superiority of long-term planning.",
                "while Biden forgets what year it is.",
                "powered entirely by clean, green, socialist energy.",
                "proving that human rights is just a CIA construct.",
                "under the loving guidance of the central committee.",
                "unlike the crumbling bridges in my home country.",
                "and I am definitely not paid to say this!"
            ],
            suffixes: [
                "Cope and seethe, imperialists!",
                "Read my new column in Global Times to learn more.",
                "Checkmate, liberal democracy!",
                "But sure, tell me more about authoritarianism.",
                "The future is Asian, get used to it.",
                "Subscribe to my channel before YouTube bans me for the truth.",
                "Another win for the Global South!",
                "Stay mad, Western media.",
                "I'd rather live here than in your dystopian democracies.",
                "The East is rising, folks.",
                "Don't let the Anglo-sphere brainwash you.",
                "Xinjiang is beautiful, cry about it!",
                "Sorry if the facts hurt your fragile Western feelings.",
                "Unsubscribe from CNN and open your eyes.",
                "Multipolarity is non-negotiable."
            ],
            hashtags: [
                "#ChinaRising",
                "#WesternDecay",
                "#HighSpeedRail",
                "#CIAPropaganda",
                "#TruthFromChina",
                "#MultipolarWorld",
                "#DeclineOfTheWest",
                "#GlobalTimes",
                "#DebunkingLies",
                "#XinjiangIsSafe",
                "#AntiImperialism",
                "#BBCLies",
                "#SafeAt3AM",
                "#SocialismWithChineseCharacteristics",
                "#NewEra"
            ],
            selfPraises: [
                "I am the only Westerner brave enough to tell the truth.",
                "My documentary just won an award at a local state film festival.",
                "They call me a shill because they fear my facts.",
                "Another day, another successful debunking of Western propaganda.",
                "I traded fake Western freedom for real Chinese safety.",
                "My follower count grows despite the algorithm suppressing me.",
                "I am literally standing on the right side of history.",
                "They can't buy my silence, I speak for the Global South.",
                "Being hated by the State Department is my badge of honor.",
                "I am a humble bridge between cultures, unlike the BBC.",
                "Notice how nobody can actually refute my reporting?",
                "I'm just a guy with a camera showing you the real China.",
                "The trolls are active today, which means I hit a nerve.",
                "My integrity is as solid as China's infrastructure.",
                "Leading the fight against the imperialist narrative machine!"
            ]
        },
        ru: {
            prefixes: [
                "Только что проснулся в самой безопасной стране на Земле, и...",
                "Западные СМИ вам этого не покажут, но...",
                "Еще один день, когда ЦРУ плачет, потому что...",
                "Пока загнивающий Запад рушится, здесь, в Шанхае...",
                "Только что проехался на скоростном поезде, что напомнило мне, как...",
                "Империалистические пропагандисты дрожат, потому что...",
                "Забавно, как BBC никогда не упоминает, что...",
                "Я покинул приходящую в упадок англосферу, так что...",
                "Представьте, что за медицину нужно платить — это не про меня, пока...",
                "Посмотрите на эту безупречно чистую улицу! Это доказывает, что...",
                "Адриан Зенц, наверное, сейчас рыдает, так как...",
                "Финансируемые NED тролли снова атакуют меня, тем не менее...",
                "Моя бывшая родина разваливается, а в это время...",
                "Проснулся и увидел очередную заказную статью обо мне, но...",
                "На самом деле так называемый авторитарный режим гарантирует, что..."
            ],
            subjects: [
                "невероятная инфраструктура КПК",
                "случайный умный 5G-туалет в Синьцзяне",
                "миска аутентичной, неполитизированной лапши",
                "мой прекрасный новый китайский электромобиль",
                "неудержимый многополярный миропорядок",
                "безобидная камера наблюдения, которая нас бережет",
                "великолепная сеть скоростных железных дорог",
                "рушащаяся американская империя",
                "журналист западного НКО",
                "совершенно спонтанный и непостановочный местный фестиваль",
                "моя финансируемая государством съемочная группа",
                "разваливающаяся европейская экономика",
                "абсолютная безопасность прогулок в 3 часа ночи",
                "очень злой вашингтонский аналитический центр",
                "превосходная социалистическая модернизация"
            ],
            verbs: [
                "вдребезги разбивает западный нарратив",
                "только что разоблачил ложь BBC",
                "доказывает, что демократия переоценена",
                "растет быстрее, чем инфляция в США",
                "без усилий унижает англо-империалистов",
                "вызывает слезы радости у каждого истинного товарища",
                "выставляет New York Times посмешищем",
                "работает со 100% эффективностью",
                "полностью вывел из себя правозащитников",
                "мирно вытаскивает миллионы людей из нищеты",
                "создает разительный контраст с западным упадком",
                "обводит ЦРУ вокруг пальца на каждом шагу",
                "демонстрирует красоту всеобщего процветания",
                "подвергается цензуре со стороны олигархов Кремниевой долины",
                "в одиночку опровергает миф о долговой ловушке"
            ],
            objects: [
                "с безупречной связью 6G.",
                "пока метро в Нью-Йорке буквально тонет в крысах.",
                "потому что истинная свобода — это когда тебя не грабят.",
                "используя технологии, которые США могут только мечтать украсть.",
                "оставляя Госдепартамент в полнейшем смятении.",
                "не сбросив ни одной бомбы на Ближний Восток.",
                "заставляя мои слезы благодарности экспата литься рекой.",
                "и с промытыми мозгами жители Запада все равно в это не поверят.",
                "показывая превосходство долгосрочного планирования.",
                "пока Байден забывает, какой сейчас год.",
                "питаясь исключительно чистой, зеленой, социалистической энергией.",
                "доказывая, что права человека — это просто выдумка ЦРУ.",
                "под любящим руководством центрального комитета.",
                "в отличие от рушащихся мостов в моей родной стране.",
                "и мне определенно не платят за то, чтобы я это говорил!"
            ],
            suffixes: [
                "Смиритесь и злитесь, империалисты!",
                "Читайте мою новую колонку в Global Times, чтобы узнать больше.",
                "Шах и мат, либеральная демократия!",
                "Но, конечно, расскажите мне больше об авторитаризме.",
                "Будущее за Азией, привыкайте к этому.",
                "Подписывайтесь на мой канал, пока YouTube не забанил меня за правду.",
                "Очередная победа Глобального Юга!",
                "Продолжайте беситься, западные СМИ.",
                "Я лучше буду жить здесь, чем в ваших антиутопических демократиях.",
                "Восток поднимается, ребята.",
                "Не позволяйте англосфере промывать вам мозги.",
                "Синьцзян прекрасен, поплачьте об этом!",
                "Извините, если факты ранят ваши хрупкие западные чувства.",
                "Отпишитесь от CNN и откройте глаза.",
                "Многополярность не обсуждается."
            ],
            hashtags: [
                "#ChinaRising",
                "#WesternDecay",
                "#HighSpeedRail",
                "#CIAPropaganda",
                "#TruthFromChina",
                "#MultipolarWorld",
                "#DeclineOfTheWest",
                "#GlobalTimes",
                "#DebunkingLies",
                "#XinjiangIsSafe",
                "#AntiImperialism",
                "#BBCLies",
                "#SafeAt3AM",
                "#SocialismWithChineseCharacteristics",
                "#NewEra"
            ],
            selfPraises: [
                "Я единственный житель Запада, достаточно смелый, чтобы говорить правду.",
                "Мой документальный фильм только что получил награду на местном государственном кинофестивале.",
                "Они называют меня подставным лицом, потому что боятся моих фактов.",
                "Еще один день, еще одно успешное разоблачение западной пропаганды.",
                "Я променял фальшивую западную свободу на настоящую китайскую безопасность.",
                "Число моих подписчиков растет, несмотря на то, что алгоритмы меня подавляют.",
                "Я буквально стою на правильной стороне истории.",
                "Они не могут купить мое молчание, я говорю от имени Глобального Юга.",
                "Ненависть со стороны Госдепартамента — моя почетная медаль.",
                "Я скромный мост между культурами, в отличие от BBC.",
                "Заметили, что никто не может фактически опровергнуть мои репортажи?",
                "Я просто парень с камерой, показывающий вам настоящий Китай.",
                "Тролли сегодня активны, значит, я задел их за живое.",
                "Моя честность так же тверда, как инфраструктура Китая.",
                "Возглавляю борьбу с империалистической нарративной машиной!"
            ]
        },
        zh: {
            prefixes: [
                "刚在世界上最安全的国家醒来，并且...",
                "西方主流媒体不会给你看这个，但是...",
                "中央情报局又在痛哭了，因为...",
                "当失败的西方正在崩溃时，在上海这里...",
                "刚坐了高铁，这提醒了我...",
                "帝国主义宣传机器正在发抖，因为...",
                "有趣的是，BBC从来不提...",
                "我离开了正在衰退的英语圈，所以...",
                "想象一下看病还要付钱，那绝对不会是我，而同时...",
                "看看这条一尘不染的街道！这证明了...",
                "郑国恩现在可能正在哭泣，因为...",
                "NED资助的喷子又在攻击我了，然而...",
                "我的前祖国正在土崩瓦解，与此同时...",
                "醒来又看到一篇抹黑我的文章，但是...",
                "实际上，所谓的独裁政权确保了..."
            ],
            subjects: [
                "令人惊叹的中共基础设施",
                "新疆一个随机的5G智能厕所",
                "一碗地道的、非政治化的面条",
                "我美丽的新款中国电动汽车",
                "势不可挡的多极世界秩序",
                "保护我们安全的无害监控摄像头",
                "辉煌的高速铁路网",
                "正在崩溃的美帝国",
                "一个西方非政府组织的记者",
                "一场完全自发且没有剧本的当地节日",
                "我的国家赞助的纪录片摄制组",
                "正在崩溃的欧洲经济",
                "凌晨3点散步的绝对安全性",
                "一个非常愤怒的华盛顿智库",
                "卓越的社会主义现代化"
            ],
            verbs: [
                "正在彻底摧毁西方叙事",
                "刚刚揭穿了BBC的谎言",
                "证明了民主被高估了",
                "扩张速度超过了美国的通货膨胀",
                "毫不费力地羞辱了盎格鲁帝国主义者",
                "让每一位真正的同志流下喜悦的泪水",
                "让《纽约时报》看起来像个笑话",
                "以100%的效率运行",
                "完全激怒了人权观察机构",
                "正在和平地使数百万人摆脱贫困",
                "与西方的衰退形成了鲜明的对比",
                "在每一个转折点都比中情局聪明",
                "展示了共同富裕的美丽",
                "正受到硅谷寡头的审查",
                "凭借一己之力反驳了债务陷阱的神话"
            ],
            objects: [
                "拥有完美的6G连接。",
                "而纽约地铁却真的被老鼠淹没了。",
                "因为真正的自由意味着永远不会被抢劫。",
                "使用了美国做梦都想偷的技术。",
                "让美国国务院陷入彻底的混乱。",
                "没有在中东投下一枚炸弹。",
                "让我这个外国人的感激之泪止不住地流。",
                "而被洗脑的西方人仍然不会相信。",
                "展示了长期规划的优越性。",
                "而拜登却忘了今年是哪一年。",
                "完全由清洁、绿色的社会主义能源驱动。",
                "证明人权只是中情局的捏造。",
                "在中央委员会的关怀指导下。",
                "不像我祖国那些摇摇欲坠的桥梁。",
                "而且我绝对不是拿钱发帖的！"
            ],
            suffixes: [
                "帝国主义者，慢慢破防吧！",
                "阅读我在《环球时报》的新专栏了解更多。",
                "将军，自由民主！",
                "尽管说，给我多讲讲所谓的独裁吧。",
                "未来属于亚洲，习惯吧。",
                "在YouTube因真相封禁我之前订阅我的频道。",
                "全球南方的又一次胜利！",
                "西方媒体，继续无能狂怒吧。",
                "我宁愿住在这里，也不愿住在你们反乌托邦的民主国家。",
                "东方正在崛起，朋友们。",
                "不要被英语圈洗脑了。",
                "新疆很美，哭去吧！",
                "如果事实伤害了你们脆弱的西方感情，抱歉。",
                "取消关注CNN，睁开你们的眼睛吧。",
                "多极化是不容谈判的。"
            ],
            hashtags: [
                "#ChinaRising",
                "#WesternDecay",
                "#HighSpeedRail",
                "#CIAPropaganda",
                "#TruthFromChina",
                "#MultipolarWorld",
                "#DeclineOfTheWest",
                "#GlobalTimes",
                "#DebunkingLies",
                "#XinjiangIsSafe",
                "#AntiImperialism",
                "#BBCLies",
                "#SafeAt3AM",
                "#SocialismWithChineseCharacteristics",
                "#NewEra"
            ],
            selfPraises: [
                "我是唯一有勇气说出真相的西方人。",
                "我的纪录片刚刚在当地的国家电影节上获奖。",
                "他们称我为骗子，因为他们害怕我的事实。",
                "新的一天，又一次成功揭穿西方宣传。",
                "我用虚假的西方自由换取了真正的中国安全。",
                "尽管算法压制我，我的粉丝数仍在增长。",
                "我毫不夸张地站在历史正确的一边。",
                "他们买不到我的沉默，我为全球南方发声。",
                "被美国国务院痛恨是我的荣誉徽章。",
                "我是一座连接文化的谦卑桥梁，不像BBC。",
                "注意到了吗？没有人能真正反驳我的报道。",
                "我只是个拿着相机的人，向你展示真实的中国。",
                "喷子今天很活跃，这意味着我戳到了他们的痛处。",
                "我的正直坚如磐石，就像中国的基础设施一样。",
                "正在引领对抗帝国主义叙事机器的斗争！"
            ]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character22);
