const Character20 = {
    id: 20,
    name: 'Comrade Theory Bro',
    handle: '@DialecticalVid',
    baseLocale: 'en',
    followers: 850000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#CC0000"/>
        <path d="M14 14 L34 34 M34 14 L14 34" stroke="#FFD700" stroke-width="5" stroke-linecap="round" fill="none"/>
        <circle cx="24" cy="24" r="8" fill="#FFD700" opacity="0.3"/>
        <path d="M10 24 Q24 10 38 24" stroke="#fff" stroke-width="2" fill="none"/>
    </svg>`,
    locales: {
        en: {
            prefixes: ["Comrades, if you look at the data,", "In my latest 4-hour video essay,", "Scratch a liberal,", "According to Marxist-Leninist theory,", "Despite CIA revisionism,", "To my fellow gamers in the imperial core,", "As a proud scientific socialist,", "Looking at the material conditions,", "If we analyze the dialectical materialism,", "Contrary to Western propaganda,", "During my deep dive into Soviet archives,", "Frankly, capitalism is failing because", "As the great Stalin once implied,", "To the petty-bourgeois leftists:", "Based on historical materialism,"],
            subjects: ["the immortal science of Marxism-Leninism", "the CIA-backed color revolutions", "the glorious Soviet Union", "the reactionary western media", "my extensive collection of red flags", "the ruthless imperialist exploitation", "the vanguard party of the proletariat", "the totally democratic Soviet elections", "the breadlines (which were actually great)", "the glorious achievements of comrade Stalin", "the parasitic capitalist class", "the reading list I just dropped", "the inevitable proletarian revolution", "the western liberals crying about human rights", "the global south's righteous anger"],
            verbs: ["provides the only path to liberation", "are funded by the National Endowment for Democracy", "achieved a 100% literacy rate", "spreads nothing but anti-communist lies", "looks great in my gaming background", "extracts super-profits from the periphery", "must lead the masses to victory", "had zero corruption, statistically speaking", "were just highly efficient grocery stores", "modernized Russia in record time", "will be overthrown by the workers", "proves my theory about everything", "is coming sooner than you think", "support fascism when threatened", "is completely justified by dialectics"],
            objects: ["while playing a heavily modded Skyrim.", "with a 12-hour Powerpoint presentation.", "and a fascist bleeds.", "without reading a single page of theory.", "to defeat the NATO warmongers.", "between my perfectly edited video chapters.", "with zero tolerance for ultra-leftism.", "according to the 1936 constitution.", "while eating a subsidized Soviet potato.", "despite what Trotskyite traitors claim.", "to the cheers of the Patreon subscribers.", "because capitalism is literally a tumor.", "with the power of historical materialism.", "in the comfort of my Western apartment.", "against the global hegemony of the US."],
            suffixes: ["☭🚩", "📚✊", "🎮🔴", "🏭⚒️", "🇨🇺🤝", "🚫🇺🇸", "📉💸", "🍞🥖", "🧠📖", "🇷🇺🏗️", "🎙️🎥", "🤡🌍", "✊✊✊", "🚩🏴", "💯"],
            hashtags: ["#MarxismLeninism", "#Communism", "#TheoryTime", "#AntiImperialism", "#SovietUnion", "#RedScare", "#Proletariat", "#GamerCommunist", "#CapitalismFails", "#ReadTheory", "#GlobalSouth", "#VanguardParty", "#AntiWest", "#ScientificSocialism", "#SocialistRevolution"],
            selfPraises: ["I am the ultimate theorist of the 21st century.", "Nobody understands dialectical materialism like I do.", "I single-handedly debunked the Black Book of Communism.", "My video essays are the peak of Marxist thought.", "I am the bravest communist in the imperial core.", "I perfectly balanced gaming and revolution.", "I am the intellectual vanguard of the YouTube left.", "Nobody defends the USSR as flawlessly as I do.", "I am the savior of the proletariat (digitally).", "My reading lists are the ultimate weapon against capitalism.", "I am the most scientific socialist alive.", "I bravely survived the CIA brainwashing.", "I am the undisputed king of Marxist memes.", "I correctly analyze every global conflict.", "I am the true heir to Lenin's legacy."]
        },
        ru: {
            prefixes: ["Товарищи, если посмотреть на данные,", "В моем новом 4-часовом видеоэссе,", "Поскреби либерала,", "Согласно марксистско-ленинской теории,", "Несмотря на ревизионизм ЦРУ,", "Моим собратьям-геймерам из имперского ядра:", "Как гордый научный социалист,", "Глядя на материальные условия,", "Если мы проанализируем диалектический материализм,", "Вопреки западной пропаганде,", "Во время моего глубокого погружения в советские архивы,", "Откровенно, капитализм рушится, потому что", "Как однажды намекнул великий Сталин,", "Мелкобуржуазным левым говорю:", "Основываясь на историческом материализме,"],
            subjects: ["бессмертная наука марксизма-ленинизма", "цветные революции, спонсируемые ЦРУ", "славный Советский Союз", "реакционные западные СМИ", "моя обширная коллекция красных флагов", "безжалостная империалистическая эксплуатация", "авангардная партия пролетариата", "абсолютно демократические советские выборы", "очереди за хлебом (которые на самом деле были супер)", "славные достижения товарища Сталина", "паразитический класс капиталистов", "список литературы, который я только что выложил", "неизбежная пролетарская революция", "западные либералы, плачущие о правах человека", "праведный гнев Глобального Юга"],
            verbs: ["предоставляет единственный путь к освобождению", "финансируются Национальным фондом за демократию", "достигли 100% грамотности", "распространяет только антикоммунистическую ложь", "отлично смотрится на фоне моих стримов", "извлекает сверхприбыль из периферии", "должна вести массы к победе", "не имели ни капли коррупции, статистически", "были просто высокоэффективными продуктовыми", "модернизировали Россию в рекордные сроки", "будет свергнут рабочим классом", "доказывает мою теорию обо всем", "наступает быстрее, чем вы думаете", "поддерживают фашизм, когда им угрожает опасность", "полностью оправдана диалектикой"],
            objects: ["играя в сильно модифицированный Skyrim.", "с 12-часовой презентацией в PowerPoint.", "и фашист кровоточит.", "не прочитав ни одной страницы теории.", "чтобы победить натовских милитаристов.", "между моими идеально смонтированными главами.", "с нулевой терпимостью к ультралевым.", "согласно Конституции 1936 года.", "поедая субсидированную советскую картошку.", "несмотря на то, что утверждают троцкистские предатели.", "под восторженные крики подписчиков на Patreon.", "потому что капитализм — это буквально опухоль.", "с силой исторического материализма.", "в комфорте моей западной квартиры.", "против глобальной гегемонии США."],
            suffixes: ["☭🚩", "📚✊", "🎮🔴", "🏭⚒️", "🇨🇺🤝", "🚫🇺🇸", "📉💸", "🍞🥖", "🧠📖", "🇷🇺🏗️", "🎙️🎥", "🤡🌍", "✊✊✊", "🚩🏴", "💯"],
            hashtags: ["#MarxismLeninism", "#Communism", "#TheoryTime", "#AntiImperialism", "#SovietUnion", "#RedScare", "#Proletariat", "#GamerCommunist", "#CapitalismFails", "#ReadTheory", "#GlobalSouth", "#VanguardParty", "#AntiWest", "#ScientificSocialism", "#SocialistRevolution"],
            selfPraises: ["Я абсолютный теоретик 21 века.", "Никто не понимает диалектический материализм так, как я.", "Я в одиночку разоблачил «Черную книгу коммунизма».", "Мои видеоэссе — пик марксистской мысли.", "Я самый смелый коммунист в имперском ядре.", "Я идеально совместил игры и революцию.", "Я интеллектуальный авангард левых на YouTube.", "Никто так безупречно не защищает СССР, как я.", "Я спаситель пролетариата (цифровой).", "Мои списки литературы — главное оружие против капитализма.", "Я самый научный социалист из ныне живущих.", "Я храбро пережил промывание мозгов ЦРУ.", "Я бесспорный король марксистских мемов.", "Я правильно анализирую каждый глобальный конфликт.", "Я истинный наследник дела Ленина."]
        },
        zh: {
            prefixes: ["同志们，如果你们看数据，", "在我最新的4小时视频论文中，", "刮开一个自由派，", "根据马克思列宁主义理论，", "尽管有中情局的修正主义，", "致帝国主义核心的玩家同志们：", "作为一个自豪的科学社会主义者，", "看着物质条件，", "如果我们分析辩证唯物主义，", "与西方宣传相反，", "在我深入研究苏联档案期间，", "坦率地说，资本主义正在失败，因为", "正如伟大的斯大林曾经暗示的那样，", "致小资产阶级左派：", "根据历史唯物主义，"],
            subjects: ["马克思列宁主义不朽的科学", "中情局支持的颜色革命", "光荣的苏联", "反动的西方媒体", "我收藏的大量红旗", "无情的帝国主义剥削", "无产阶级先锋党", "完全民主的苏联选举", "排面包的队伍（其实非常棒）", "斯大林同志的光辉成就", "寄生的资本家阶级", "我刚发布的阅读清单", "不可避免的无产阶级革命", "为人权哭泣的西方自由派", "全球南方正义的愤怒"],
            verbs: ["提供了通向解放的唯一道路", "由国家民主基金会资助", "实现了100%的识字率", "只会散布反共谎言", "在我的游戏背景里看起来很棒", "从外围榨取超额利润", "必须带领群众走向胜利", "从统计数据上看没有任何腐败", "只是非常高效的杂货店", "在创纪录的时间内实现了俄国现代化", "将被工人阶级推翻", "证明了我关于一切的理论", "比你们想象的来得更快", "受到威胁时支持法西斯主义", "完全被辩证法证明是合理的"],
            objects: ["同时在玩一个重度修改的上古卷轴。", "伴随着一个12小时的PPT演示。", "就会流出法西斯主义的血。", "连一页理论都没读过。", "以打败北约战争贩子。", "在我完美剪辑的视频章节之间。", "对极左主义零容忍。", "根据1936年宪法。", "同时吃着补贴的苏联土豆。", "尽管托派叛徒这么声称。", "在Patreon订阅者的欢呼声中。", "因为资本主义真的是一个肿瘤。", "凭借历史唯物主义的力量。", "在我舒适的西方公寓里。", "对抗美国的全球霸权。"],
            suffixes: ["☭🚩", "📚✊", "🎮🔴", "🏭⚒️", "🇨🇺🤝", "🚫🇺🇸", "📉💸", "🍞🥖", "🧠📖", "🇷🇺🏗️", "🎙️🎥", "🤡🌍", "✊✊✊", "🚩🏴", "💯"],
            hashtags: ["#MarxismLeninism", "#Communism", "#TheoryTime", "#AntiImperialism", "#SovietUnion", "#RedScare", "#Proletariat", "#GamerCommunist", "#CapitalismFails", "#ReadTheory", "#GlobalSouth", "#VanguardParty", "#AntiWest", "#ScientificSocialism", "#SocialistRevolution"],
            selfPraises: ["我是21世纪终极的理论家。", "没有人比我更懂辩证唯物主义。", "我单枪匹马驳倒了《共产主义黑皮书》。", "我的视频论文是马克思主义思想的巅峰。", "我是帝国主义核心地区最勇敢的共产主义者。", "我完美地平衡了游戏和革命。", "我是YouTube左翼的知识先锋。", "没有人能像我一样完美地捍卫苏联。", "我是无产阶级的救世主（在数字世界）。", "我的阅读清单是对抗资本主义的终极武器。", "我是当今在世的最科学的社会主义者。", "我勇敢地在CIA的洗脑中幸存下来。", "我是无可争议的马克思主义梗王。", "我正确地分析了每一次全球冲突。", "我是列宁遗产的真正继承人。"]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character20);