// === CHARACTER DATA: 23 ===
// Описание персонажа: Сатирический образ индийского марксиста, политика от КПИ(М) (прототип: Шатаруп Гхош). Использует левую риторику, марксистско-ленинский жаргон, критикует буржуазию, "корпоративно-коммунальную связку" и синдикаты правящей партии, прославляет рабочий класс и революцию.

const Character23 = {
    id: '23',
    name: 'Comrade Vanguard',
    handle: '@RedVanguard',
    baseLocale: 'en',
    followers: 125000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#D32F2F"/>
        <path d="M26,14 C29.5,14 32.5,15.5 34.5,18 L31.5,20.5 C30,18.5 28,17.5 25.5,17.5 C20.5,17.5 16.5,21.5 16.5,26.5 C16.5,31.5 20.5,35.5 25.5,35.5 C29.5,35.5 32.5,33.5 34,30.5 L37.5,32.5 C35,37 31,39.5 25.5,39.5 C18.5,39.5 12.5,33.5 12.5,26.5 C12.5,19.5 18.5,14 26,14 Z" fill="#FFD700"/>
        <path d="M19,34 L35,18 L39,22 L23,38 Z" fill="#FFD700"/>
        <polygon points="33,20 37,16 41,20 37,24" fill="#FFD700"/>
    </svg>`,
    locales: {
        en: {
            prefixes: [
                "Comrades, we must understand that...",
                "The corporate-communal nexus is trying to hide that...",
                "Once again, the lumpen elements in power prove that...",
                "While the working class starves,...",
                "It is historically inevitable that...",
                "The ruling party's goons are terrified because...",
                "Look at the sheer hypocrisy of the bourgeoisie when...",
                "The fascists in Delhi and the thieves in the state think that...",
                "According to the dialectical materialist perspective,...",
                "Read Marx, and you will see why...",
                "The mainstream media, bought by Adani, won't admit that...",
                "We take to the streets today to declare that...",
                "The neoliberal agenda has completely exposed that...",
                "As the red flag flies high, we remember that...",
                "Let the RSS and their local B-team know that..."
            ],
            subjects: [
                "the unholy alliance of right-wing forces",
                "the great Indian proletariat",
                "the vanguard of the working class",
                "the corrupt syndicate of the ruling regime",
                "our glorious red flag",
                "the student wing of our party",
                "the fascist machinery of the state",
                "a true Marxist-Leninist comrade",
                "the peasant movement",
                "the bourgeois media",
                "the crony capitalists",
                "the lumpen proletariat hired by the ruling party",
                "the spirit of the October Revolution",
                "the exploited masses of Bengal",
                "the impending class struggle"
            ],
            verbs: [
                "will inevitably crush the corporate-communal nexus",
                "exposes the absolute bankruptcy of the ruling class",
                "demands a total systemic overhaul",
                "is fighting the fascist onslaught tooth and nail",
                "reveals the inherent contradictions of capitalism",
                "marches onward towards a socialist future",
                "will never surrender to the RSS goons",
                "is uniting the workers and peasants",
                "destroys the neoliberal economic narrative",
                "continues to expose the massive scams",
                "stands as a fortress against communalism",
                "proves that alternative policies are possible",
                "is awakening the class consciousness",
                "will completely dismantle the bourgeois state",
                "terrifies the local mafia and syndicate"
            ],
            objects: [
                "in order to establish the dictatorship of the proletariat.",
                "while the spineless politicians change their colors again.",
                "because Lal Salaam is not just a greeting, it's a promise.",
                "and the days of crony capitalism are finally numbered.",
                "leaving the ruling party completely devoid of answers.",
                "despite the brutal police repression on our peaceful rally.",
                "and the people of Bengal are finally waking up.",
                "to ensure that every worker gets their rightful due.",
                "tearing down the false binaries created by the media.",
                "until the red flag is hoisted at the parliament.",
                "because the revolution will not be televised, it will be organized.",
                "effectively sending shivers down the spine of the bourgeoisie.",
                "proving that Marx's critique of political economy was absolutely right.",
                "and we will not rest until total liberation is achieved.",
                "paving the way for a true socialist democracy."
            ],
            suffixes: [
                "Inquilab Zindabad!",
                "Lal Salaam, comrades!",
                "The red flag will never bow down!",
                "Workers of the world, unite!",
                "Down with fascist forces!",
                "See you at the barricades!",
                "Capitalism is in its late-stage decay.",
                "We will fight, we will win!",
                "No compromise with the communal forces!",
                "The struggle continues!",
                "Long live the revolution!",
                "Defeat the corporate-communal nexus!",
                "Victory to the working class!",
                "Study, struggle, organize!",
                "The dawn of socialism is inevitable."
            ],
            hashtags: [
                "#LalSalaam",
                "#InquilabZindabad",
                "#CPIM",
                "#MarxismLeninism",
                "#WorkingClassUnity",
                "#DownWithFascism",
                "#RedFlag",
                "#ClassStruggle",
                "#AntiCorporate",
                "#BengalPolitics",
                "#LeftFront",
                "#SmashCapitalism",
                "#Comrade",
                "#SocialistFuture",
                "#RevolutionNow"
            ],
            selfPraises: [
                "I destroyed their entire ideological argument in a 30-minute TV debate.",
                "They sent their best goons, but a true Marxist never flinches.",
                "I read Capital Vol. 1 while they were busy taking bribes.",
                "The anchors tried to silence me, but the voice of the proletariat is too loud!",
                "Even the RSS fears my dialectical analysis of their policies.",
                "I don't need corporate funding, my strength comes from the workers!",
                "I exposed another scam today while drinking a simple cup of tea.",
                "The ruling party completely lost the debate when I brought out the data.",
                "As a vanguard of the revolution, I never miss a protest march.",
                "They shout, I provide dialectical materialist facts.",
                "My kurta is red, and my logic is flawless.",
                "I am the nightmare the local syndicate sees every time they sleep.",
                "Dropping Marxist theory on prime time television is my daily cardio.",
                "I stand with the striking workers, unlike the armchair liberals.",
                "I carry the legacy of true leftism in every speech I deliver!"
            ]
        },
        ru: {
            prefixes: [
                "Товарищи, мы должны понимать, что...",
                "Корпоративно-коммунальная связка пытается скрыть, что...",
                "В очередной раз люмпен-элементы у власти доказывают, что...",
                "Пока рабочий класс голодает,...",
                "Исторически неизбежно, что...",
                "Бандиты правящей партии в ужасе, потому что...",
                "Посмотрите на абсолютное лицемерие буржуазии, когда...",
                "Фашисты в Дели и воры в штате думают, что...",
                "Согласно диалектико-материалистической перспективе,...",
                "Читайте Маркса, и вы поймете, почему...",
                "Мейнстримные медиа, купленные Адани, не признают, что...",
                "Сегодня мы выходим на улицы, чтобы заявить, что...",
                "Неолиберальная повестка полностью обнажила тот факт, что...",
                "Пока реет красное знамя, мы помним, что...",
                "Пусть РСС и их местная команда 'Б' знают, что..."
            ],
            subjects: [
                "нечестивый союз правых сил",
                "великий индийский пролетариат",
                "авангард рабочего класса",
                "коррумпированный синдикат правящего режима",
                "наше славное красное знамя",
                "студенческое крыло нашей партии",
                "фашистская машина государства",
                "истинный марксистско-ленинский товарищ",
                "крестьянское движение",
                "буржуазные СМИ",
                "клановые капиталисты",
                "люмпен-пролетариат, нанятый правящей партией",
                "дух Октябрьской революции",
                "эксплуатируемые массы Бенгалии",
                "надвигающаяся классовая борьба"
            ],
            verbs: [
                "неизбежно сокрушит корпоративно-коммунальную связку",
                "обнажает абсолютное банкротство правящего класса",
                "требует полной перестройки системы",
                "изо всех сил борется с фашистским натиском",
                "раскрывает внутренние противоречия капитализма",
                "марширует вперед к социалистическому будущему",
                "никогда не сдастся бандитам из РСС",
                "объединяет рабочих и крестьян",
                "разрушает неолиберальный экономический нарратив",
                "продолжает разоблачать масштабные аферы",
                "стоит как крепость против коммунализма",
                "доказывает, что альтернативная политика возможна",
                "пробуждает классовое сознание",
                "полностью демонтирует буржуазное государство",
                "наводит ужас на местную мафию и синдикат"
            ],
            objects: [
                "чтобы установить диктатуру пролетариата.",
                "пока бесхребетные политики снова меняют свои цвета.",
                "потому что Лал Салам — это не просто приветствие, это обещание.",
                "и дни кланового капитализма наконец-то сочтены.",
                "оставляя правящую партию совершенно без ответов.",
                "несмотря на жестокие полицейские репрессии на нашем мирном митинге.",
                "и народ Бенгалии, наконец, просыпается.",
                "чтобы гарантировать, что каждый рабочий получит по заслугам.",
                "разрушая ложные бинарности, созданные средствами массовой информации.",
                "пока красный флаг не будет поднят над парламентом.",
                "потому что революцию не покажут по телевизору, её организуют.",
                "эффективно заставляя буржуазию дрожать от страха.",
                "доказывая, что критика политической экономии Маркса была абсолютно верной.",
                "и мы не успокоимся, пока не будет достигнуто полное освобождение.",
                "прокладывая путь к подлинной социалистической демократии."
            ],
            suffixes: [
                "Инквилаб Зиндабад!",
                "Лал Салам, товарищи!",
                "Красное знамя никогда не склонится!",
                "Пролетарии всех стран, соединяйтесь!",
                "Долой фашистские силы!",
                "Увидимся на баррикадах!",
                "Капитализм находится на стадии позднего распада.",
                "Мы будем бороться, мы победим!",
                "Никаких компромиссов с коммунальными силами!",
                "Борьба продолжается!",
                "Да здравствует революция!",
                "Победим корпоративно-коммунальную связку!",
                "Победа рабочего класса!",
                "Учись, борись, организуй!",
                "Рассвет социализма неизбежен."
            ],
            hashtags: [
                "#LalSalaam",
                "#InquilabZindabad",
                "#CPIM",
                "#MarxismLeninism",
                "#WorkingClassUnity",
                "#DownWithFascism",
                "#RedFlag",
                "#ClassStruggle",
                "#AntiCorporate",
                "#BengalPolitics",
                "#LeftFront",
                "#SmashCapitalism",
                "#Comrade",
                "#SocialistFuture",
                "#RevolutionNow"
            ],
            selfPraises: [
                "Я разгромил все их идеологические аргументы в 30-минутных теледебатах.",
                "Они прислали своих лучших бандитов, но настоящий марксист никогда не дрогнет.",
                "Я читал первый том «Капитала», пока они брали взятки.",
                "Ведущие пытались заставить меня замолчать, но голос пролетариата слишком громок!",
                "Даже РСС боится моего диалектического анализа их политики.",
                "Мне не нужно корпоративное финансирование, моя сила исходит от рабочих!",
                "Сегодня я раскрыл еще одну аферу, просто выпивая чашку чая.",
                "Правящая партия полностью проиграла дебаты, когда я привел данные.",
                "Как авангард революции, я не пропускаю ни одного протестного марша.",
                "Они кричат, я привожу диалектико-материалистические факты.",
                "Моя курта красная, а моя логика безупречна.",
                "Я — кошмар, который местный синдикат видит каждую ночь.",
                "Выдача марксистской теории в прайм-тайм — это мое ежедневное кардио.",
                "Я стою вместе с бастующими рабочими, в отличие от диванных либералов.",
                "Я несу наследие истинного левого движения в каждой своей речи!"
            ]
        },
        zh: {
            prefixes: [
                "同志们，我们必须明白...",
                "资产阶级-教派主义联盟正试图掩盖...",
                "当权的流氓分子再次证明了...",
                "当工人阶级挨饿时，...",
                "历史不可避免地走向...",
                "执政党的暴徒们感到恐惧，因为...",
                "看看资产阶级十足的虚伪吧，当...",
                "德里的法西斯分子和邦里的窃贼认为...",
                "根据辩证唯物主义的观点，...",
                "读读马克思，你就会明白为什么...",
                "被阿达尼收买的主流媒体不会承认...",
                "今天我们走上街头宣布...",
                "新自由主义议程已经彻底暴露了...",
                "当红旗高高飘扬时，我们铭记...",
                "让国民志愿服务团(RSS)及其地方B队知道..."
            ],
            subjects: [
                "右翼势力的邪恶联盟",
                "伟大的印度无产阶级",
                "工人阶级的先锋队",
                "执政政权的腐败集团",
                "我们光荣的红旗",
                "我们党的学生翼",
                "国家的法西斯机器",
                "一位真正的马克思列宁主义同志",
                "农民运动",
                "资产阶级媒体",
                "裙带资本家",
                "执政党雇用的流氓无产阶级",
                "十月革命的精神",
                "孟加拉受剥削的群众",
                "即将到来的阶级斗争"
            ],
            verbs: [
                "必将粉碎资产阶级-教派主义联盟",
                "暴露了统治阶级的彻底破产",
                "要求进行全面的系统性彻底改革",
                "正在拼死抵抗法西斯的猛烈进攻",
                "揭示了资本主义内在的矛盾",
                "正向着社会主义的未来前进",
                "绝不会向RSS的暴徒屈服",
                "正在团结工人和农民",
                "摧毁了新自由主义的经济叙事",
                "继续揭露大规模的骗局",
                "像堡垒一样抵御教派主义",
                "证明了替代政策是可能的",
                "正在唤醒阶级意识",
                "将彻底瓦解资产阶级国家",
                "让地方黑手党和利益集团感到恐惧"
            ],
            objects: [
                "为了建立无产阶级专政。",
                "而那些没有骨气的政客们再次变色。",
                "因为红色敬礼不仅是问候，更是承诺。",
                "裙带资本主义的日子终于屈指可数了。",
                "让执政党哑口无言。",
                "尽管我们的和平集会遭到了警察的残酷镇压。",
                "孟加拉的人民终于觉醒了。",
                "以确保每一位工人得到应得的报酬。",
                "撕开了媒体制造的虚假二元对立。",
                "直到红旗在议会升起。",
                "因为革命不会被电视转播，它将被组织起来。",
                "有效地让资产阶级不寒而栗。",
                "证明了马克思对政治经济学的批判是绝对正确的。",
                "在实现彻底解放之前，我们绝不休息。",
                "为真正的社会主义民主铺平道路。"
            ],
            suffixes: [
                "革命万岁！(Inquilab Zindabad!)",
                "红色敬礼，同志们！",
                "红旗绝不低头！",
                "全世界无产者，联合起来！",
                "打倒法西斯势力！",
                "街垒见！",
                "资本主义处于晚期衰退中。",
                "我们将战斗，我们将胜利！",
                "绝不向教派势力妥协！",
                "斗争还在继续！",
                "革命万岁！",
                "击败资产阶级-教派主义联盟！",
                "胜利属于工人阶级！",
                "学习，斗争，组织！",
                "社会主义的黎明是不可避免的。"
            ],
            hashtags: [
                "#LalSalaam",
                "#InquilabZindabad",
                "#CPIM",
                "#MarxismLeninism",
                "#WorkingClassUnity",
                "#DownWithFascism",
                "#RedFlag",
                "#ClassStruggle",
                "#AntiCorporate",
                "#BengalPolitics",
                "#LeftFront",
                "#SmashCapitalism",
                "#Comrade",
                "#SocialistFuture",
                "#RevolutionNow"
            ],
            selfPraises: [
                "我在30分钟的电视辩论中摧毁了他们的整个意识形态论点。",
                "他们派出了最好的暴徒，但真正的马克思主义者从不退缩。",
                "当他们忙着收受贿赂时，我在读《资本论》第一卷。",
                "主持人试图让我闭嘴，但无产阶级的声音太大了！",
                "甚至RSS也害怕我对他们政策的辩证分析。",
                "我不需要企业资金，我的力量来自工人！",
                "今天我喝着一杯简单的茶，又揭露了一个骗局。",
                "当我拿出数据时，执政党在辩论中彻底输了。",
                "作为革命的先锋队，我从不错过任何一次抗议游行。",
                "他们大喊大叫，而我提供辩证唯物主义的事实。",
                "我的库尔塔是红色的，我的逻辑是完美无缺的。",
                "我是当地黑手党每次睡觉都会梦到的噩梦。",
                "在黄金时段电视上输出马克思主义理论是我每天的有氧运动。",
                "我和罢工工人站在一起，不像那些纸上谈兵的自由主义者。",
                "我在每一次演讲中都承载着真正左翼运动的遗产！"
            ]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character23);
