const Character21 = {
    id: 21,
    name: 'Amnesty Spox',
    handle: '@KabulEmiratePR',
    baseLocale: 'en',
    followers: 600000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#fff"/>
        <rect x="0" y="0" width="48" height="16" fill="#000"/>
        <rect x="0" y="32" width="48" height="16" fill="#006400"/>
        <circle cx="24" cy="24" r="6" fill="#000"/>
        <path d="M24 18 V30 M18 24 H30" stroke="#fff" stroke-width="2"/>
    </svg>`,
    locales: {
        en: {
            prefixes: ["Praise be to God,", "According to the general amnesty,", "Contrary to Western lies,", "As the official voice of the Emirate,", "To the international community:", "Despite the fake news media,", "By the grace of Allah,", "In the spirit of Islamic brotherhood,", "After consulting the supreme leadership,", "Rest assured, we are not a threat to anyone,", "Looking at the peaceful streets of Kabul,", "To our sisters in the universities:", "With absolute transparency,", "Under the framework of pure Sharia,", "Frankly, the Western media is confused because", "As I tweeted yesterday,"],
            subjects: ["the general amnesty", "the Islamic Emirate", "our peaceful brothers", "the Western feminist propaganda", "the compulsory hijab", "the completely voluntary closing of girls' schools", "the glorious victory of 2021", "the Sharia-compliant stoning", "the illegal foreign assets", "the pure Islamic society", "the death to America chants", "my perfectly formatted English tweet", "the destruction of Western idols", "the progressive ban on music", "the totally fair tribal courts", "the mighty Taliban fighters"],
            verbs: ["is a testament to our mercy", "guarantees absolute security", "are integrating perfectly", "is a malicious lie", "is a symbol of female empowerment", "is a temporary administrative measure", "shows our commitment to peace", "will resume next spring, God willing", "must be returned immediately", "will be a beacon for the world", "are just cultural expressions", "proves our excellent diplomatic skills", "is a necessary purification", "protects the youth from sin", "deliver swift and holy justice", "are honored as national heroes"],
            objects: ["while wearing my pristine white turban.", "in the completely empty national parks.", "before my next Zoom call with the UN.", "with zero interference from women.", "according to the principles of 1996.", "under the watchful eye of the morality police.", "to the complete silence of the West.", "with absolute respect for human rights (Sharia version).", "while hanging gays from cranes.", "using only the most diplomatic English vocabulary.", "after a long day of banning things.", "in the glorious Islamic caliphate.", "to trigger the decadent Westerners.", "with a comforting pat on the head.", "for the sake of our eternal souls.", "before evening prayers at the mosque."],
            suffixes: ["🕌🤍", "📜⚔️", "🚫🎤", "🇦🇫🦅", "🧕🚪", "🛑🎵", "🤝🇺🇳", "✊🌑", "👳‍♂️📱", "🚫👖", "📖🕌", "🇦🇓✨", "🚫🇺🇸", "⚖️🪨", "🤲🌙", "💯"],
            hashtags: ["#IslamicEmirate", "#GeneralAmnesty", "#ShariaLaw", "#KabulPR", "#AfghanPeace", "#NoThreatToAnyone", "#PureIslam", "#WestStopLying", "#BanMusic", "#MoralityPolice", "#TalibanV2", "#HijabIsEmpowerment", "#GirlsSchoolsClosed", "#DeathToAmerica", "#AfghanLivesMatter", "#EmirateDiplomacy"],
            selfPraises: ["I am the ultimate master of diplomatic spin.", "Nobody tweets as eloquently as I do.", "I am the voice of the glorious Emirate.", "My English vocabulary is unmatched in Kabul.", "I single-handedly convinced the UN we are peaceful.", "I am the savior of Afghan public relations.", "I am the most moderate extremist alive.", "Nobody can spin a stoning better than me.", "My white turban is a symbol of pure PR.", "I bravely tell the West exactly what they want to hear.", "I am the undisputed king of contradictory statements.", "My press conferences are modern masterpieces.", "I successfully rebranded terror as liberation.", "I am the greatest spokesman in the Islamic world.", "I flawlessly execute the supreme leader's tweets.", "I am the ultimate bridge between the 7th century and Twitter."]
        },
        ru: {
            prefixes: ["Хвала Богу,", "Согласно общей амнистии,", "Вопреки западной лжи,", "Как официальный голос Эмирата,", "Международному сообществу говорю:", "Несмотря на фейковые новости СМИ,", "Милостью Аллаха,", "В духе исламского братства,", "После консультаций с верховным руководством,", "Будьте уверены, мы не представляем угрозы ни для кого,", "Глядя на мирные улицы Кабула,", "Нашим сестрам в университетах говорю:", "С абсолютной прозрачностью,", "В рамках чистого шариата,", "Откровенно, западные СМИ в замешательстве, потому что", "Как я написал в твиттере вчера,"],
            subjects: ["общая амнистия", "Исламский Эмират", "наши мирные братья", "западная феминистская пропаганда", "обязательный хиджаб", "полностью добровольное закрытие школ для девочек", "славная победа 2021 года", "забивание камнями по шариату", "незаконные иностранные активы", "чистое исламское общество", "лозунги 'Смерть Америке'", "мой идеально отформатированный твит на английском", "уничтожение западных идолов", "прогрессивный запрет на музыку", "абсолютно справедливые племенные суды", "могучие бойцы Талибана"],
            verbs: ["является свидетельством нашего милосердия", "гарантирует абсолютную безопасность", "идеально интегрируются", "является злобной клеветой", "является символом расширения прав женщин", "является временной административной мерой", "показывает нашу приверженность миру", "возобновится следующей весной, если угодно Богу", "должны быть немедленно возвращены", "станет маяком для всего мира", "являются просто культурным самовыражением", "доказывает наши превосходные дипломатические навыки", "является необходимым очищением", "защищает молодежь от греха", "вершат быстрое и святое правосудие", "почитаются как национальные герои"],
            objects: ["нося свой безупречный белый тюрбан.", "в абсолютно пустых национальных парках.", "перед моим следующим зум-звонком с ООН.", "с нулевым вмешательством женщин.", "согласно принципам 1996 года.", "под бдительным оком полиции нравов.", "при полном молчании Запада.", "с абсолютным уважением к правам человека (версия шариата).", "вешая геев на кранах.", "используя только самую дипломатичную английскую лексику.", "после долгого дня запретов.", "в славном исламском халифате.", "чтобы подразнить растленных западников.", "с утешительным похлопыванием по голове.", "ради наших вечных душ.", "перед вечерней молитвой в мечети."],
            suffixes: ["🕌🤍", "📜⚔️", "🚫🎤", "🇦🇫🦅", "🧕🚪", "🛑🎵", "🤝🇺🇳", "✊🌑", "👳‍♂️📱", "🚫👖", "📖🕌", "🇦🇓✨", "🚫🇺🇸", "⚖️🪨", "🤲🌙", "💯"],
            hashtags: ["#IslamicEmirate", "#GeneralAmnesty", "#ShariaLaw", "#KabulPR", "#AfghanPeace", "#NoThreatToAnyone", "#PureIslam", "#WestStopLying", "#BanMusic", "#MoralityPolice", "#TalibanV2", "#HijabIsEmpowerment", "#GirlsSchoolsClosed", "#DeathToAmerica", "#AfghanLivesMatter", "#EmirateDiplomacy"],
            selfPraises: ["Я абсолютный мастер дипломатического пиара.", "Никто не твитит так красноречиво, как я.", "Я голос славного Эмирата.", "Мой словарный запас английского не имеет равных в Кабуле.", "Я в одиночку убедил ООН, что мы мирные.", "Я спаситель афганских общественных связей.", "Я самый умеренный экстремист из ныне живущих.", "Никто не умеет так подать забивание камнями, как я.", "Мой белый тюрбан — символ чистого пиара.", "Я смело говорю Западу именно то, что они хотят услышать.", "Я бесспорный король противоречивых заявлений.", "Мои пресс-конференции — современные шедевры.", "Я успешно ребрендировал террор как освобождение.", "Я величайший пресс-секретарь в исламском мире.", "Я безупречно исполняю твиты верховного лидера.", "Я идеальный мост между 7-м веком и Твиттером."]
        },
        zh: {
            prefixes: ["赞美归于真主，", "根据大赦令，", "与西方的谎言相反，", "作为酋长国的官方发言人，", "致国际社会：", "尽管有虚假新闻媒体，", "托真主的福，", "本着伊斯兰兄弟情义的精神，", "在与最高领导层协商后，", "请放心，我们对任何人都不构成威胁，", "看着喀布尔和平的街道，", "对我们在大学的姐妹们说：", "带着绝对的透明度，", "在纯粹的伊斯兰教法框架下，", "坦率地说，西方媒体感到困惑，因为", "正如我昨天在推特上发的，"],
            subjects: ["大赦令", "伊斯兰酋长国", "我们和平的兄弟们", "西方女权主义宣传", "强制头巾", "完全自愿关闭女子学校", "2021年的光荣胜利", "符合伊斯兰教法的石刑", "非法的外国资产", "纯洁的伊斯兰社会", "美国去死的口号", "我格式完美的英文推文", "摧毁西方偶像", "禁止音乐的进步举措", "绝对公平的部落法庭", "强大的塔利班战士"],
            verbs: ["是我们仁慈的证明", "保证绝对的安全", "正在完美融入", "是恶意的谎言", "是女性赋权的象征", "是一项临时行政措施", "表明我们对和平的承诺", "如果真主意欲，将于明年春天恢复", "必须立即归还", "将成为世界的灯塔", "只是文化表达", "证明我们出色的外交技巧", "是必要的净化", "保护年轻人免受罪恶", "实施迅速而神圣的正义", "被尊为国家英雄"],
            objects: ["同时戴着我洁白无瑕的头巾。", "在完全空无一人的国家公园里。", "在我与联合国的下一次Zoom会议之前。", "在女性零干预的情况下。", "根据1996年的原则。", "在劝善惩恶部的监视下。", "在西方的完全沉默中。", "绝对尊重人权（伊斯兰教法版）。", "同时把同性恋吊在起重机上。", "只使用最外交的英语词汇。", "在漫长的一天禁令之后。", "在光荣的伊斯兰哈里发国里。", "为了激怒堕落的西方人。", "安慰地拍拍头。", "为了我们永恒的灵魂。", "在清真寺的晚祷之前。"],
            suffixes: ["🕌🤍", "📜⚔️", "🚫🎤", "🇦🇫🦅", "🧕🚪", "🛑🎵", "🤝🇺🇳", "✊🌑", "👳‍♂️📱", "🚫👖", "📖🕌", "🇦🇓✨", "🚫🇺🇸", "⚖️🪨", "🤲🌙", "💯"],
            hashtags: ["#IslamicEmirate", "#GeneralAmnesty", "#ShariaLaw", "#KabulPR", "#AfghanPeace", "#NoThreatToAnyone", "#PureIslam", "#WestStopLying", "#BanMusic", "#MoralityPolice", "#TalibanV2", "#HijabIsEmpowerment", "#GirlsSchoolsClosed", "#DeathToAmerica", "#AfghanLivesMatter", "#EmirateDiplomacy"],
            selfPraises: ["我是外交公关的终极大师。", "没有人能像我一样雄辩地发推。", "我是光荣酋长国的声音。", "我的英语词汇在喀布尔无与伦比。", "我单枪匹马说服联合国我们是和平的。", "我是阿富汗公关的救世主。", "我是当今最温和的极端分子。", "没有人能比我更好地为石刑洗白。", "我的白头巾是纯粹公关的象征。", "我勇敢地对西方说他们想听的话。", "我是自相矛盾声明的无可争议的国王。", "我的新闻发布会是现代杰作。", "我成功地将恐怖重塑为解放。", "我是伊斯兰世界最伟大的发言人。", "我完美地执行了最高领导人的推文。", "我是7世纪与Twitter之间的终极桥梁。"]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character21);