// === CHARACTER DATA: 18 ===
// Описание персонажа: Сатирический прототип - левый социалист, пацифист, садовод-любитель, защитник люков и марксистских идей.

const Character18 = {
    id: 18,
    name: 'Allotment Marxist',
    handle: '@AllotmentMarxist',
    baseLocale: 'en',
    followers: 2500000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#E11B22"/>
        <circle cx="24" cy="24" r="12" fill="#fff"/>
        <path d="M24 14 L18 30 H30 Z" fill="#E11B22"/>
        <path d="M24 24 Q24 20 26 20 Q28 20 28 22" stroke="#006400" stroke-width="2" fill="none"/>
    </svg>`,
    locales: {
        en: {
            prefixes: ["My honourable friends,", "Looking at my marrows at the allotment,", "Despite the smear campaign by the media,", "To the billionaire press barons:", "According to the collective will of the members,", "In my thirty years on the backbenches,", "Let us be absolutely clear,", "While sipping a cup of herbal tea,", "Unlike the Blairite warmongers,", "If we nationalise the water companies,", "Under a true socialist framework,", "To the workers on the picket line:", "Despite the right-wing saboteurs in the PLP,", "As a lifelong anti-war campaigner,", "Speaking truth to power,", "If we just sit down and talk for ten hours,"],
            subjects: ["the ruthless billionaire class", "my perfectly grown organic tomatoes", "the brutal NATO aggression", "the heroic workers of Islington", "a fully automated luxury communism", "the evil Tory austerity", "the local manhole cover society", "the completely unbiased Kremlin media", "the Blairite Red Tories", "the disarmament of the Trident nuclear submarines", "the free broadband for all policy", "the warmongering military-industrial complex", "my endless manifesto of empty promises", "the glorious Bolivarian revolution", "the radical Transformation Fund", "the nuclear codes of NATO"],
            verbs: ["must be taxed into oblivion", "taste exactly like socialism", "must be condemned immediately", "deserve a six-week paid holiday", "is the only way forward", "is literally killing the poor", "is my favourite Tuesday hobby", "is far more trustworthy than the BBC", "have destroyed our beloved party", "will bring about world peace", "is a basic human right", "must be dismantled for profit", "will be delivered, honestly, maybe, eventually", "is a model of true democracy", "will magically fund itself", "should be handed over to President Putin"],
            objects: ["while adjusting my Lenin cap.", "to the polite applause of my local Momentum branch.", "with zero intention of ever taking power.", "during my morning ride on a public bicycle.", "before the next endless NEC meeting.", "with absolute moral clarity.", "while typing a letter of protest.", "because war is never the answer.", "under the banner of the many, not the few.", "without a single drop of imperialist blood.", "with a nod to my friend Hugo.", "to the absolute horror of the establishment.", "while repairing my socialist bicycle.", "for the sake of the global proletariat.", "in a completely beige and unwinnable way.", "before I go back to my allotment."],
            suffixes: ["🌹✊", "🍅🌱", "☮️🇬🇧", "🚲🚂", "🚫☢️", "📉💰", "🤝🇨🇺", "📰🚫", "✊🚩", "🍵🍃", "✊🏽✊🏾✊🏿", "👷‍♂️⚒️", "🕊️🌍", "📉🇺🇸", "🇵🇸🤝", "💯"],
            hashtags: ["#ForTheMany", "#AllotmentMarxist", "#SocialistSunday", "#StopTheWar", "#FreePalestine", "#AntiWar", "#ToriesOut", "#Nationalise", "#NoTrident", "#Momentum", "#RedOctober", "#AntiAusterity", "#PeaceNotWar", "#WorkersRights", "#FreeBroadband", "#SocialistFuture"],
            selfPraises: ["I am the purest socialist in Britain.", "Nobody grows marrows like I do.", "I am the ultimate man of peace.", "I single-handedly mobilised the youth.", "My moral compass is absolutely flawless.", "I am the most stubborn man in politics.", "Nobody opposes imperialist wars better than me.", "I am the true voice of the working class.", "My allotment is a utopian commune.", "I bravely fought the Blairite saboteurs.", "I am the undisputed king of the picket line.", "Nobody understands Venezuelan economics like I do.", "I am the most principled man alive.", "I fearlessly refuse to apologize for anything.", "I am the spiritual father of Momentum.", "I am the most honest Marxist in Islington."]
        },
        ru: {
            prefixes: ["Мои досточтимые друзья,", "Глядя на свои кабачки на огороде,", "Несмотря на кампанию по очернению в СМИ,", "Медиамагнатам-миллиардерам говорю:", "Согласно коллективной воле членов партии,", "За мои тридцать лет на задних скамьях парламента,", "Давайте будем абсолютно ясны,", "Потягивая чашечку травяного чая,", "В отличие от блээритов-милитаристов,", "Если мы национализируем водоснабжение,", "В рамках истинного социализма,", "Рабочим на линии пикета говорю:", "Несмотря на саботаж правых в парламенте,", "Как пожизненный антивоенный активист,", "Говоря правду власти,", "Если мы просто сядем и поговорим часов десять,"],
            subjects: ["безжалостный класс миллиардеров", "мои идеально выращенные органические помидоры", "жестокая агрессия НАТО", "героические рабочие Ислингтона", "полностью автоматизированный роскошный коммунизм", "злое ториевское сокращение расходов", "местное общество люков", "абсолютно непредвзятые кремлевские СМИ", "блээриты-красные тори", "разоружение атомных подлодок Trident", "бесплатный интернет для всех", "милитаристский военно-промышленный комплекс", "мой бесконечный манифест пустых обещаний", "славная боливарианская революция", "радикальный Фонд трансформации", "ядерные коды НАТО"],
            verbs: ["должны быть обложены налогами до нищеты", "на вкус как настоящий социализм", "должны быть немедленно осуждены", "заслуживают шестинедельного оплачиваемого отпуска", "единственный путь вперед", "буквально убивает бедных", "мое любимое развлечение по вторникам", "гораздо заслуживают больше доверия, чем Би-би-си", "уничтожили нашу любимую партию", "принесут мир во всем мире", "базовое право человека", "должны быть демонтированы ради прибыли", "будут выполнены, честно, возможно, в итоге", "модель истинной демократии", "волшебным образом окупит себя", "следует передать президенту Путину"],
            objects: ["поправляя свою кепку Ленина.", "под вежливые аплодисменты местного отделения Моментум.", "без малейшего намерения брать власть.", "во время утренней поездки на общественном велосипеде.", "перед следующим бесконечным заседанием исполкома.", "с абсолютной моральной ясностью.", "печатая письмо с протестом.", "потому что война — никогда не выход.", "под знаменем многих, а не немногих.", "без единой капли империалистической крови.", "кивая моему другу Уго.", "к абсолютному ужасу истеблишмента.", "пока чиню свой социалистический велосипед.", "ради глобального пролетариата.", "совершенно блекло и безнадежно.", "прежде чем я вернусь на свой огород."],
            suffixes: ["🌹✊", "🍅🌱", "☮️🇬🇧", "🚲🚂", "🚫☢️", "📉💰", "🤝🇨🇺", "📰🚫", "✊🚩", "🍵🍃", "✊🏽✊🏾✊🏿", "👷‍♂️⚒️", "🕊️🌍", "📉🇺🇸", "🇵🇸🤝", "💯"],
            hashtags: ["#ForTheMany", "#AllotmentMarxist", "#SocialistSunday", "#StopTheWar", "#FreePalestine", "#AntiWar", "#ToriesOut", "#Nationalise", "#NoTrident", "#Momentum", "#RedOctober", "#AntiAusterity", "#PeaceNotWar", "#WorkersRights", "#FreeBroadband", "#SocialistFuture"],
            selfPraises: ["Я самый чистый социалист в Британии.", "Никто не выращивает кабачки так, как я.", "Я абсолютный миротворец.", "Я в одиночку мобилизовал молодежь.", "Мой моральный компас абсолютно безупречен.", "Я самый упрямый человек в политике.", "Никто не противостоит империалистическим войнам лучше меня.", "Я истинный голос рабочего класса.", "Мой огород — это утопическая коммуна.", "Я храбро сражался с саботажниками-блээритами.", "Я бесспорный король пикетов.", "Никто не понимает венесуэльскую экономику так, как я.", "Я самый принципиальный человек из ныне живущих.", "Я бесстрашно отказываюсь извиняться за что-либо.", "Я духовный отец Моментум.", "Я самый честный марксист в Ислингтоне."]
        },
        zh: {
            prefixes: ["我尊敬的朋友们，", "看着我的菜地里的西葫芦，", "尽管媒体在进行抹黑运动，", "对亿万富翁媒体大亨们说：", "根据党员的集体意愿，", "在我担任后座议员的这三十年里，", "让我们绝对清楚，", "品尝着一杯花草茶时，", "与布莱尔派战争贩子不同，", "如果我们将水务公司国有化，", "在真正的社会主义框架下，", "对纠察线上的工人们说：", "尽管议会中有右翼破坏者，", "作为一名终身的反战活动家，", "向权力说真话，", "如果我们只是坐下来谈上十个小时，"],
            subjects: ["无情的亿万富翁阶级", "我种出的完美有机西红柿", "北约的野蛮侵略", "伊斯灵顿的英雄工人们", "全自动化奢华共产主义", "邪恶的保守党紧缩政策", "当地的井盖协会", "完全不偏不倚的克里姆林宫媒体", "布莱尔派的红保守党", "三叉戟核潜艇的裁军", "全民免费宽带政策", "好战的军工复合体", "我那写满空头支票的无限宣言", "光荣的玻利瓦尔革命", "激进的转型基金", "北约的核代码"],
            verbs: ["必须被征税直到破产", "尝起来就像社会主义", "必须立即受到谴责", "理应获得六周的带薪假期", "是唯一的前进道路", "简直是在杀害穷人", "是我最喜欢的周二消遣", "比BBC值得信赖得多", "摧毁了我们亲爱的政党", "将带来世界和平", "是一项基本人权", "必须为了利润而被拆解", "终将兑现，老实说，也许，最终会", "是真正民主的典范", "将奇迹般地自我筹资", "应该交给普京总统"],
            objects: ["同时整理着我的列宁帽。", "在当地Momentum分支礼貌的掌声中。", "完全没有掌权的意图。", "在我早晨骑公共自行车时。", "在下一次无休止的全国执行委员会会议之前。", "带着绝对的道德清晰度。", "同时打着一封抗议信。", "因为战争绝不是答案。", "在为了多数人而不是少数人的旗帜下。", "不流一滴帝国主义的血。", "向我的朋友乌戈点头致意。", "让建制派感到绝对的恐惧。", "同时修理我的社会主义自行车。", "为了全球无产阶级的利益。", "以一种完全平淡且无法获胜的方式。", "在我回到我的菜地之前。"],
            suffixes: ["🌹✊", "🍅🌱", "☮️🇬🇧", "🚲🚂", "🚫☢️", "📉💰", "🤝🇨🇺", "📰🚫", "✊🚩", "🍵🍃", "✊🏽✊🏾✊🏿", "👷‍♂️⚒️", "🕊️🌍", "📉🇺🇸", "🇵🇸🤝", "💯"],
            hashtags: ["#ForTheMany", "#AllotmentMarxist", "#SocialistSunday", "#StopTheWar", "#FreePalestine", "#AntiWar", "#ToriesOut", "#Nationalise", "#NoTrident", "#Momentum", "#RedOctober", "#AntiAusterity", "#PeaceNotWar", "#WorkersRights", "#FreeBroadband", "#SocialistFuture"],
            selfPraises: ["我是英国最纯粹的社会主义者。", "没有人能像我一样种西葫芦。", "我是终极的和平使者。", "我单枪匹马动员了年轻人。", "我的道德指南针绝对完美无瑕。", "我是政界最固执的人。", "没有人比我更善于反对帝国主义战争。", "我是工人阶级真正的声音。", "我的菜地是一个乌托邦公社。", "我勇敢地与布莱尔派破坏者作斗争。", "我是纠察线无可争议的国王。", "没有人比我更懂委内瑞拉经济。", "我是世上最有原则的人。", "我无畏地拒绝为任何事道歉。", "我是Momentum的精神之父。", "我是伊斯灵顿最诚实的马克思主义者。"]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character18);