// === CHARACTER DATA: 12 ===
// Описание персонажа: Сатирический прототип - леворадикальная прогрессистка, бывший бармен, любительница историй в Instagram, социализма и налогов для богатых.

const Character12 = {
    id: 12,
    name: 'Bronx Comradar',
    handle: '@SocialistSiren',
    baseLocale: 'en',
    followers: 8300000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#cc0000"/>
        <path d="M8 30 Q24 10 40 30 Q24 44 8 30 Z" fill="#fff"/>
        <path d="M8 30 Q24 38 40 30" stroke="#cc0000" stroke-width="3" fill="none"/>
        <circle cx="24" cy="22" r="5" fill="#cc0000"/>
    </svg>`,
    locales: {
        en: {
            prefixes: ["Like, literally,", "In case you missed my IG Live,", "As a former bartender from the Bronx,", "The establishment Democrats are shaking because", "To my haters in the GOP:", "According to the Green New Deal,", "Honestly, the system is rigged, so", "While cooking my instant mac and cheese,", "Speaking as a democratic socialist,", "Despite what the billionaire-owned media says,", "If we don't act in 12 years,", "After crying at the border fence,", "Let me break down the marginal tax rates:", "Unlike the fascist Republicans,", "To the billionaires in their ivory towers:", "With all due respect to the Constitution,"],
            subjects: ["the ultra-rich billionaire class", "the catastrophic climate change", "my glossy red Met Gala dress", "the racist immigration system", "the establishment corporate Democrats", "the fascist Supreme Court", "my complicated tax the rich plan", "the heroic members of the Squad", "the evil fossil fuel executives", "my rusty old congressional salary", "the systemic oppression in America", "the legendary Bronx working class", "the capitalist patriarchy", "the right-wing disinformation machine", "a totally relatable working-class struggle", "the marginalized queer communities"],
            verbs: ["must pay their fair share", "will literally end the world in 12 years", "was a brilliant feminist statement", "is basically concentration camps", "are terrified of my progressive power", "needs to be entirely abolished", "will magically fund universal healthcare", "are taking over the Democratic Party", "deserve to be put in prison", "is barely enough to survive in DC", "is the root of all evil", "deserves a massive government subsidy", "is destroying our reproductive rights", "spreads nothing but racist lies", "requires a 70% income tax rate", "must be protected at all costs"],
            objects: ["while dancing in a viral college video.", "because socialism works in Venezuela.", "with zero understanding of basic economics.", "while wearing my sponsored designer heels.", "to the cheering of my Twitter echo chamber.", "before the oceans literally boil over.", "in a totally relatable Instagram story.", "because capitalism is a disease.", "without actually reading the bill.", "while renting a luxury apartment in DC.", "with the power of intersectional feminism.", "because housing is a human right.", "using my signature giant red lipstick.", "despite my massive Amazon Prime wishlist.", "to the applause of my Gen Z followers.", "while sipping a $16 artisanal cocktail."],
            suffixes: ["✊🌹", "📉💸", "🌍🔥", "💄👗", "🗽🗽", "🤡🇺🇸", "🗽🥂", "🤷‍♀️", "🛑✋", "📖✨", "🏳️‍🌈✊", "🚂🇺🇸", "🔥👑", "☕️🤡", "🇺🇸🐘", "🔴🤝"],
            hashtags: ["#TaxTheRich", "#GreenNewDeal", "#TheSquad", "#DemocraticSocialist", "#AbolishICE", "#EatTheRich", "#ClimateEmergency", "#ProgressiveWave", "#MedicareForAll", "#BronxPower", "#MetGalaMarxist", "#Resist", "#CancelCapitalism", "#IntersectionalFeminism", "#FairShare", "#GenZSocialist"],
            selfPraises: ["I am the future of the Democratic Party.", "I am the most brilliant economist in Congress.", "I single-handedly saved the climate agenda.", "My fashion choices are revolutionary acts.", "I am the ultimate voice of the working class.", "Nobody understands marginal tax rates like I do.", "I am the most relatable politician in history.", "I am the fearless leader of the Squad.", "I bravely fought the establishment (while in power).", "I am the intellectual powerhouse of the left.", "My Instagram Lives are modern masterpieces.", "I am the champion of the marginalized.", "I successfully trolled all the billionaires.", "I am the savior of American democracy.", "I am the most influential Latina in America.", "I am the ultimate Gen Z political icon."]
        },
        ru: {
            prefixes: ["Как бы буквально,", "Если вы пропустили мой прямой эфир в IG,", "Как бывший бармен из Бронкса,", "Истеблишмент демократов дрожит, потому что", "Моим хейтерам из Республиканской партии:", "Согласно Новому зеленому курсу,", "Честно говоря, система сфальсифицирована, поэтому", "Пока готовила свой растворимый макароны с сыром,", "Говоря как демократический социалист,", "Вопреки тому, что говорят медиа миллиардеров,", "Если мы не начнем действовать через 12 лет,", "После того как поплакала у забора на границе,", "Позвольте мне объяснить предельные налоговые ставки:", "В отличие от фашистских республиканцев,", "Миллиардерам в их башнях из слоновой кости говорю:", "При всем уважении к Конституции,"],
            subjects: ["ультрабогатый класс миллиардеров", "катастрофическое изменение климата", "мое глянцевое красное платье с Met Gala", "расистская иммиграционная система", "истеблишмент корпоративных демократов", "фашистский Верховный суд", "мой сложный план обложить налогом богатых", "героические члены Отряда", "злые руководители ископаемого топлива", "моя ржавая старая зарплата конгрессмена", "системное угнетение в Америке", "легендарный рабочий класс Бронкса", "капиталистическая патриархия", "правая машина дезинформации", "полностью понятная борьба рабочего класса", "маргинализированные квир-сообщества"],
            verbs: ["должны платить свою справедливую долю", "буквально уничтожат мир через 12 лет", "был блестящим феминистским заявлением", "это в основном концентрационные лагеря", "напуганы моей прогрессивной властью", "должен быть полностью упразднен", "волшебным образом профинансирует всеобщее здравоохранение", "берут под контроль Демократическую партию", "заслуживают того, чтобы их посадили в тюрьму", "едва хватает на выживание в Вашингтоне", "является корнем всех зол", "заслуживает массовых государственных субсидий", "уничтожает наши репродуктивные права", "распространяет только расистскую ложь", "требует 70% подоходного налога", "должны быть защищены любой ценой"],
            objects: ["танцуя в вирусном студенческом видео.", "потому что социализм работает в Венесуэле.", "с нулевым пониманием базовой экономики.", "пока ношу свои спонсорские дизайнерские каблуки.", "под восторженные крики моего эхо-шоу в Твиттере.", "пока океаны буквально не закипят.", "в совершенно понятной истории в Instagram.", "потому что капитализм — это болезнь.", "вообще не читая законопроект.", "арендуя роскошную квартиру в Вашингтоне.", "с силой интерсекционального феминизма.", "потому что жилье — это право человека.", "используя свою фирменную гигантскую красную помаду.", "несмотря на мой огромный список желаний на Amazon Prime.", "под аплодисменты моих подписчиков из поколения Z.", "потягивая крафтовый коктейль за 16 долларов."],
            suffixes: ["✊🌹", "📉💸", "🌍🔥", "💄👗", "🗽🗽", "🤡🇺🇸", "🗽🥂", "🤷‍♀️", "🛑✋", "📖✨", "🏳️‍🌈✊", "🚂🇺🇸", "🔥👑", "☕️🤡", "🇺🇸🐘", "🔴🤝"],
            hashtags: ["#TaxTheRich", "#GreenNewDeal", "#TheSquad", "#DemocraticSocialist", "#AbolishICE", "#EatTheRich", "#ClimateEmergency", "#ProgressiveWave", "#MedicareForAll", "#BronxPower", "#MetGalaMarxist", "#Resist", "#CancelCapitalism", "#IntersectionalFeminism", "#FairShare", "#GenZSocialist"],
            selfPraises: ["Я будущее Демократической партии.", "Я самый блестящий экономист в Конгрессе.", "Я в одиночку спасла климатическую повестку.", "Мой выбор одежды — революционные акты.", "Я абсолютный голос рабочего класса.", "Никто не понимает предельные налоговые ставки так, как я.", "Я самый понятный политик в истории.", "Я бесстрашный лидер Отряда.", "Я смело сражалась с истеблишментом (находясь у власти).", "Я интеллектуальная мощь левых.", "Мои прямые эфиры в Instagram — современные шедевры.", "Я чемпионка маргиналов.", "Я успешно троллила всех миллиардеров.", "Я спасительница американской демократии.", "Я самая влиятельная латиноамериканка в Америке.", "Я абсолютная политическая икона поколения Z."]
        },
        zh: {
            prefixes: ["就像，毫不夸张地说，", "如果你错过了我的IG直播，", "作为一个来自布朗克斯的前酒保，", "建制派民主党人在发抖，因为", "致共和党里的黑子们：", "根据绿色新政，", "老实说，系统是被操纵的，所以", "在煮我的速食芝士通心粉时，", "作为一个民主社会主义者，", "尽管亿万富翁拥有的媒体这么说，", "如果我们不在12年内采取行动，", "在边境栅栏哭泣之后，", "让我来拆解边际税率：", "与法西斯共和党人不同，", "致象牙塔里的亿万富翁们：", "出于对宪法的充分尊重，"],
            subjects: ["超级富有的亿万富翁阶级", "灾难性的气候变化", "我闪亮的Met Gala红裙", "种族主义的移民系统", "建制派企业民主党人", "法西斯最高法院", "我复杂的向富人征税计划", "小队的英勇成员们", "邪恶的化石燃料高管", "我那点微薄的国会议员工资", "美国的系统性压迫", "传奇的布朗克斯工人阶级", "资本主义父权制", "右翼虚假信息机器", "完全能引起共鸣的工人阶级斗争", "被边缘化的酷儿群体"],
            verbs: ["必须支付他们应得的份额", "将在12年内字面意义上毁灭世界", "是一个绝妙的女权主义宣言", "基本上就是集中营", "害怕我的进步力量", "需要被彻底废除", "将奇迹般地为全民医保提供资金", "正在接管民主党", "应该被送进监狱", "在华盛顿勉强够生存", "是万恶之源", "应该获得大规模政府补贴", "正在摧毁我们的生育权", "只会散布种族主义谎言", "需要70%的所得税率", "必须不惜一切代价保护"],
            objects: ["同时在一段疯传的大学视频中跳舞。", "因为社会主义在委内瑞拉行得通。", "对基本经济学毫无了解。", "同时穿着我赞助的名牌高跟鞋。", "在我的推特回音壁的欢呼声中。", "在海洋字面意义上沸腾之前。", "在一个完全能引起共鸣的Instagram故事中。", "因为资本主义是一种疾病。", "根本没有读过法案。", "同时在华盛顿租着豪华公寓。", "凭借交叉性女性主义的力量。", "因为住房是人权。", "使用我标志性的巨型红唇膏。", "尽管我有庞大的亚马逊Prime心愿单。", "在我的Z世代粉丝的掌声中。", "同时啜饮一杯16美元的精调鸡尾酒。"],
            suffixes: ["✊🌹", "📉💸", "🌍🔥", "💄👗", "🗽🗽", "🤡🇺🇸", "🗽🥂", "🤷‍♀️", "🛑✋", "📖✨", "🏳️‍🌈✊", "🚂🇺🇸", "🔥👑", "☕️🤡", "🇺🇸🐘", "🔴🤝"],
            hashtags: ["#TaxTheRich", "#GreenNewDeal", "#TheSquad", "#DemocraticSocialist", "#AbolishICE", "#EatTheRich", "#ClimateEmergency", "#ProgressiveWave", "#MedicareForAll", "#BronxPower", "#MetGalaMarxist", "#Resist", "#CancelCapitalism", "#IntersectionalFeminism", "#FairShare", "#GenZSocialist"],
            selfPraises: ["我是民主党的未来。", "我是国会中最杰出的经济学家。", "我单枪匹马拯救了气候议程。", "我的时尚选择是革命行为。", "我是工人阶级的终极代言人。", "没有人比我更懂边际税率。", "我是历史上最能引起共鸣的政治家。", "我是小队无畏的领袖。", "我勇敢地对抗了建制派（同时掌权）。", "我是左翼的智力引擎。", "我的Instagram直播是现代杰作。", "我是边缘化人群的捍卫者。", "我成功地喷了所有亿万富翁。", "我是美国民主的救世主。", "我是美国最有影响力的拉丁裔。", "我是终极Z世代政治偶像。"]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character12);