// === CHARACTER DATA: 11 ===
// Описание персонажа: Сатирический прототип - правый национал-консерватор, вышедший из элит, любитель мемуаров и "защитник Ржавого пояса".

const Character11 = {
    id: 11,
    name: 'Appalachia Apex',
    handle: '@HollerVC',
    baseLocale: 'en',
    followers: 2200000,
    icon: `<svg viewBox="0 0 48 48" preserveAspectRatio="none" style="width:100%;height:100%;display:block;">
        <rect x="0" y="0" width="48" height="48" fill="#8B0000"/>
        <polygon points="0,48 16,20 32,48" fill="#fff"/>
        <polygon points="16,48 32,20 48,48" fill="#fff" opacity="0.8"/>
        <path d="M20 10 V18 M16 14 H24" stroke="#FFD700" stroke-width="3" fill="none"/>
    </svg>`,
    locales: {
        en: {
            prefixes: ["Speaking as a reformed coastal elite,", "To the childless cat ladies:", "In my Appalachian grandmother's voice,", "Looking at the hollowed-out Rust Belt,", "Despite the mainstream media's panic,", "With my Catholic faith guiding me,", "After making millions in Silicon Valley,", "To the forgotten men and women of Ohio:", "Let's be honest about the cultural decay,", "Unlike the progressive elites,", "In my brand new populist persona,", "While writing my Oscar-nominated memoir,", "According to the true MAGA faithful,", "Having escaped the woke corporate world,", "To the radical leftists in academia:", "Frankly, my fellow hillbillies,"],
            subjects: ["the miserable childless cat ladies", "the anti-family left-wing agenda", "the opioid crisis in the hollers", "my wildly profitable hillbilly memoir", "the soulless Silicon Valley oligarchs", "the forgotten factory workers of Middletown", "the radical gender ideology in schools", "the Ivy League out-of-touch snobs", "the traditional American family unit", "the rapid decline of Christian values", "the globalist vampires in Washington", "my lucrative venture capital fund", "the completely broken border", "the drag queen story hours", "the proud Scots-Irish heritage", "the disastrous Biden administration"],
            verbs: ["are destroying our civilization", "need to mind their own business", "deserves a massive populist uprising", "perfectly explains why Trump won", "are funding the degeneracy", "have been abandoned by the elites", "is a sick attack on our children", "will never understand real America", "must be defended at all costs", "is the root of all our problems", "are selling out our jobs to China", "proves I am a man of the people", "is an insult to our sovereignty", "should be outlawed immediately", "is the backbone of this great nation", "is turning our country into a dystopia"],
            objects: ["while drinking a room-temperature Diet Mountain Dew.", "in the abandoned steel mills of Ohio.", "to the applause of conservative donors.", "before my next mandatory Catholic confession.", "with zero respect for the woke mob.", "in the deepest hollers of Kentucky.", "to protect our innocent kids.", "while they sip overpriced lattes in Brooklyn.", "because family is the only thing that matters.", "with my Bible in one hand.", "while collecting massive VC paychecks.", "despite my recent coastal elite makeover.", "with a border wall taller than the Appalachians.", "before they brainwash another generation.", "with a shotgun and a case of beer.", "while the forgotten men finally rise up."],
            suffixes: ["🐱🇺🇸", "🧗‍♂️📖", "🇺🇸🦅", "🍼👨‍👩‍👧‍👦", "🙏✝️", "🤡🌍", "🚫💄", "💰🤝", "🏭📉", "🇺🇸✨", "👢🤠", "💯", "🍻🦝", "🇺🇸🧱", "📖🎬", "🔴🐘"],
            hashtags: ["#ChildlessCatLadies", "#HillbillyElegy", "#MAGA", "#AmericaFirst", "#RustBeltRising", "#FamilyValues", "#CatholicConvert", "#SiliconValleyHypocrite", "#ForgottenMen", "#PopulistVC", "#AntiWoke", "#OhioPatriot", "#AppalachianPride", "#Trump2024", "#DietMountainDew", "#StopTheLeft"],
            selfPraises: ["I am the intellectual savior of the Rust Belt.", "I single-handedly explained Trump to the elites.", "I am the ultimate champion of the working class.", "My memoir is the greatest American book ever written.", "I am the most authentic hillbilly in the Senate.", "I am the only one brave enough to attack cat ladies.", "I am a fiercely devoted family man.", "I successfully transitioned from snob to populist.", "I am the smartest venture capitalist in Ohio.", "Nobody understands the opioid crisis like I do.", "I am the true voice of Appalachia.", "I am the warrior our Christian nation needs.", "I am the epitome of the American Dream.", "I am the left's worst nightmare.", "I am the greatest Catholic convert in history.", "I am the undisputed heir to the MAGA throne."]
        },
        ru: {
            prefixes: ["Говоря как исправившийся прибрежный элитарий,", "Бесплодным кошатницам говорю:", "Голосом моей бабушки из Аппалачей,", "Глядя на опустошенный Ржавый пояс,", "Несмотря на панику мейнстримных СМИ,", "С верой в католическое учение,", "Заработав миллионы в Кремниевой долине,", "Забытым мужчинам и женщинам Огайо говорю:", "Будем честны насчет культурного упадка,", "В отличие от прогрессивных элит,", "В моем совершенно новом популистском амплуа,", "Пока писал свой номинированный на Оскар мемуар,", "По словам истинных сторонников MAGA,", "Сбежав от вок-корпоративного мира,", "Радикальным левым в академической среде говорю:", "Честно говоря, мои собратья-хиллбилли,"],
            subjects: ["несчастные бездетные кошатницы", "антиcемейная левая повестка", "опиоидный кризис в горах", "моя невероятно прибыльная книга-мемуар", "бессердечные олигархи из Кремниевой долины", "забытые рабочие заводов Мидлтауна", "радикальная гендерная идеология в школах", "оторванные от реальности снобы из Лиги Плюща", "традиционная американская семья", "стремительный упадок христианских ценностей", "глобалистские вампиры в Вашингтоне", "мой прибыльный венчурный фонд", "абсолютно сломанная граница", "сеансы чтения сказок дрэг-квинами", "гордое шотландско-ирландское наследие", "катастрофическая администрация Байдена"],
            verbs: ["уничтожают нашу цивилизацию", "должны заниматься своими делами", "заслуживает массового популистского восстания", "идеально объясняет, почему победил Трамп", "финансируют деградацию", "были брошены элитами на произвол судьбы", "является больной атакой на наших детей", "никогда не поймут настоящую Америку", "должна защищаться любой ценой", "является корнем всех наших проблем", "продают наши рабочие места Китаю", "доказывает, что я человек из народа", "является оскорблением нашего суверенитета", "следует немедленно запретить", "является основой этой великой нации", "превращает нашу страну в антиутопию"],
            objects: ["попивая теплую диетическую Mountain Dew.", "на заброшенных сталелитейных заводах Огайо.", "под аплодисменты консервативных спонсоров.", "перед следующей обязательной католической исповедью.", "с нулевым уважением к вок-толпе.", "в самых глубоких ущельях Кентукки.", "чтобы защитить наших невинных детей.", "пока они потягивают дорогущий латте в Бруклине.", "потому что семья — это единственное, что имеет значение.", "с Библией в одной руке.", "получая огромные зарплаты в венчурном фонде.", "несмотря на мой недавний макияж в стиле элит.", "со стеной на границе выше Аппалачей.", "пока они не промыли мозги еще одному поколению.", "с дробовиком и ящиком пива.", "пока забытые люди наконец не поднимутся."],
            suffixes: ["🐱🇺🇸", "🧗‍♂️📖", "🇺🇸🦅", "🍼👨‍👩‍👧‍👦", "🙏✝️", "🤡🌍", "🚫💄", "💰🤝", "🏭📉", "🇺🇸✨", "👢🤠", "💯", "🍻🦝", "🇺🇸🧱", "📖🎬", "🔴🐘"],
            hashtags: ["#ChildlessCatLadies", "#HillbillyElegy", "#MAGA", "#AmericaFirst", "#RustBeltRising", "#FamilyValues", "#CatholicConvert", "#SiliconValleyHypocrite", "#ForgottenMen", "#PopulistVC", "#AntiWoke", "#OhioPatriot", "#AppalachianPride", "#Trump2024", "#DietMountainDew", "#StopTheLeft"],
            selfPraises: ["Я интеллектуальный спаситель Ржавого пояса.", "Я в одиночку объяснил Трампа элитам.", "Я абсолютный чемпион рабочего класса.", "Мои мемуары — величайшая американская книга из написанных.", "Я самый настоящий хиллбилли в Сенате.", "Я единственный, у кого хватило смелости напасть на кошатниц.", "Я яростно преданный семье человек.", "Я успешно превратился из сноба в популиста.", "Я самый умный венчурный инвестор в Огайо.", "Никто не понимает опиоидный кризис так, как я.", "Я истинный голос Аппалачей.", "Я воин, в котором нуждается наша христианская нация.", "Я воплощение Американской мечты.", "Я худший кошмар для левых.", "Я величайший католический неофит в истории.", "Я бесспорный наследник трона MAGA."]
        },
        zh: {
            prefixes: ["作为一个改过自新的沿海精英，", "致那些没有孩子的养猫女士：", "用我阿巴拉契亚祖母的声音，", "看着被掏空的铁锈地带，", "尽管主流媒体感到恐慌，", "在我的天主教信仰指引下，", "在硅谷赚了几百万之后，", "对俄亥俄州被遗忘的男男女女说：", "让我们诚实地面对文化衰退，", "与那些进步派精英不同，", "以我全新的人民党人形象，", "在写我那本获奥斯卡提名的回忆录时，", "根据真正的MAGA信徒的说法，", "逃离了觉醒的企业界之后，", "对学术界激进左派说：", "坦白说，我的乡巴佬同胞们，"],
            subjects: ["悲惨的没有孩子的养猫女士", "反家庭的左翼议程", "峡谷里的阿片类药物危机", "我那本利润丰厚的乡巴佬回忆录", "毫无灵魂的硅谷寡头", "米德尔敦被遗忘的工厂工人", "学校里激进的性别意识形态", "脱离常春藤名校的势利眼", "传统的美国家庭单位", "基督教价值观的迅速衰落", "华盛顿的全球主义吸血鬼", "我利润丰厚的风险投资基金", "彻底崩溃的边境", "变装皇后讲故事活动", "骄傲的苏格兰-爱尔兰遗产", "灾难性的拜登政府"],
            verbs: ["正在摧毁我们的文明", "需要管好她们自己的事", "应该引发一场大规模的人民起义", "完美解释了为什么特朗普赢了", "正在资助堕落行为", "被精英们抛弃了", "是对我们孩子的病态攻击", "永远不会理解真正的美国", "必须不惜一切代价保卫", "是我们所有问题的根源", "正在把我们的工作出卖给中国", "证明我是人民的一员", "是对我们主权的侮辱", "应该被立即取缔", "是这个伟大国家的脊梁", "正在把我们的国家变成反乌托邦"],
            objects: ["同时喝着常温的健怡激浪。", "在俄亥俄州废弃的钢铁厂里。", "在保守派捐助者的掌声中。", "在我下一次强制性的天主教告解之前。", "对觉醒暴民毫无尊重。", "在肯塔基州最深的峡谷里。", "为了保护我们无辜的孩子。", "而他们在布鲁克林喝着昂贵的拿铁。", "因为家庭是唯一重要的事情。", "一手拿着我的圣经。", "同时收取巨额风投薪水。", "尽管我最近做了沿海精英的打扮。", "建一堵比阿巴拉契亚山脉还高的边境墙。", "在他们给下一代洗脑之前。", "带着一把猎枪和一箱啤酒。", "直到被遗忘的人们最终崛起。"],
            suffixes: ["🐱🇺🇸", "🧗‍♂️📖", "🇺🇸🦅", "🍼👨‍👩‍👧‍👦", "🙏✝️", "🤡🌍", "🚫💄", "💰🤝", "🏭📉", "🇺🇸✨", "👢🤠", "💯", "🍻🦝", "🇺🇸🧱", "📖🎬", "🔴🐘"],
            hashtags: ["#ChildlessCatLadies", "#HillbillyElegy", "#MAGA", "#AmericaFirst", "#RustBeltRising", "#FamilyValues", "#CatholicConvert", "#SiliconValleyHypocrite", "#ForgottenMen", "#PopulistVC", "#AntiWoke", "#OhioPatriot", "#AppalachianPride", "#Trump2024", "#DietMountainDew", "#StopTheLeft"],
            selfPraises: ["我是铁锈地带的智力救世主。", "我单枪匹马向精英们解释了特朗普。", "我是工人阶级的终极冠军。", "我的回忆录是有史以来最伟大的美国书籍。", "我是参议院中最地道的乡巴佬。", "我是唯一敢攻击养猫女士的勇士。", "我是一个极其忠诚的家庭男人。", "我成功从势利眼转型为人民党人。", "我是俄亥俄州最聪明的风险投资家。", "没有人比我更懂阿片类药物危机。", "我是阿巴拉契亚真正的声音。", "我是我们基督教国家需要的战士。", "我是美国梦的缩影。", "我是左派最糟糕的噩梦。", "我是历史上最伟大的天主教皈依者。", "我是MAGA王座无可争议的继承人。"]
        }
    }
};

// === REGISTRATION ===
window.THRULALA_CHARACTERS = window.THRULALA_CHARACTERS || [];
window.THRULALA_CHARACTERS.push(Character11);